//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPlayground.EF_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VocabularyEntity : DbContext
    {
        public VocabularyEntity()
            : base("name=VocabularyEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<exam_detail> exam_detail { get; set; }
        public DbSet<exam_master> exam_master { get; set; }
        public DbSet<student> student { get; set; }
        public DbSet<vocabulary> vocabulary { get; set; }
    }
}
